apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app
  targetCPUUtilizationPercentage: 85
